/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.punyal.jrad.test;

/**
 *
 * @author gamer
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        tagSecretKey = new javax.swing.JLabel();
        secretKey = new javax.swing.JTextField();
        tagServerIP = new javax.swing.JLabel();
        serverIP = new javax.swing.JTextField();
        tagUserName = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        tagUserPassword = new javax.swing.JLabel();
        userPassword = new javax.swing.JTextField();
        tagCallingStationID = new javax.swing.JLabel();
        callingStationID = new javax.swing.JTextField();
        tagCalledStationID = new javax.swing.JLabel();
        calledStationID = new javax.swing.JTextField();
        tagOpt1 = new javax.swing.JLabel();
        opt1 = new javax.swing.JTextField();
        tagOpt2 = new javax.swing.JLabel();
        opt2 = new javax.swing.JTextField();
        tagOpt4 = new javax.swing.JLabel();
        tagOpt3 = new javax.swing.JLabel();
        opt3 = new javax.swing.JTextField();
        Opt4 = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();

        jLabel3.setText("Server IP");

        jTextField3.setText("jTextField1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tagSecretKey.setText("NAS Secret Key");

        secretKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tagServerIP.setText("Server IP");

        serverIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serverIP.setToolTipText("");
        serverIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverIPActionPerformed(evt);
            }
        });

        tagUserName.setText("User Name");

        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tagUserPassword.setText("User Password");

        userPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tagCallingStationID.setText("Calling Station ID");

        callingStationID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tagCalledStationID.setText("Called Station ID");

        calledStationID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tagOpt1.setText("Opt 1");

        opt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opt1.setText("Not used");
        opt1.setToolTipText("");

        tagOpt2.setText("Opt 2");

        opt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opt2.setText("Not used");

        tagOpt4.setText("Opt 4");

        tagOpt3.setText("Opt 3");

        opt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opt3.setText("Not used");

        Opt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Opt4.setText("Not used");

        buttonSend.setText("Send");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagSecretKey)
                    .addComponent(tagServerIP)
                    .addComponent(tagOpt2)
                    .addComponent(tagOpt3)
                    .addComponent(tagOpt4)
                    .addComponent(tagOpt1)
                    .addComponent(tagCalledStationID)
                    .addComponent(tagCallingStationID)
                    .addComponent(tagUserPassword)
                    .addComponent(tagUserName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverIP)
                    .addComponent(secretKey)
                    .addComponent(userName)
                    .addComponent(userPassword)
                    .addComponent(callingStationID)
                    .addComponent(calledStationID)
                    .addComponent(opt1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(Opt4)
                    .addComponent(opt3)
                    .addComponent(opt2))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSend)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagServerIP)
                    .addComponent(serverIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagSecretKey)
                    .addComponent(secretKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagUserName)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagUserPassword)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagCallingStationID)
                    .addComponent(callingStationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagCalledStationID)
                    .addComponent(calledStationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagOpt1)
                    .addComponent(opt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagOpt2)
                    .addComponent(opt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagOpt3)
                    .addComponent(opt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagOpt4)
                    .addComponent(Opt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverIPActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Opt4;
    private javax.swing.JButton buttonSend;
    private javax.swing.JTextField calledStationID;
    private javax.swing.JTextField callingStationID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField opt1;
    private javax.swing.JTextField opt2;
    private javax.swing.JTextField opt3;
    private javax.swing.JTextField secretKey;
    private javax.swing.JTextField serverIP;
    private javax.swing.JLabel tagCalledStationID;
    private javax.swing.JLabel tagCallingStationID;
    private javax.swing.JLabel tagOpt1;
    private javax.swing.JLabel tagOpt2;
    private javax.swing.JLabel tagOpt3;
    private javax.swing.JLabel tagOpt4;
    private javax.swing.JLabel tagSecretKey;
    private javax.swing.JLabel tagServerIP;
    private javax.swing.JLabel tagUserName;
    private javax.swing.JLabel tagUserPassword;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userPassword;
    // End of variables declaration//GEN-END:variables
}
